### PR TITLE
Fix #441.

### LINKED ISSUE #441: Numbered and bullet point lists not showing.
Hi Bas,

Shoehorn issue https://github.com/gjb2048/moodle-theme_shoehorn/issues/25 also applies to Bootstrap in the M3.1 Stable branch.  All down to missing margins.  When I sort there I'll patch here too.

G

### PR DESCRIPTION
**Pull request by gjb2048**
Hi Bas,

My fix for #441.  I know I can push directly as have permission but thought you should review it instead.

Cheers,

Gareth

### CODE REVIEW

**Comment by gjb2048** [comment]
This is the result:

2016-08-23 18_33_17-start

**Comment by bmbrands** [comment]
Thanks Gareth,

Before I pull this into the repo I want to do a full test for this one. The <ul> tag is a tricky one in Moodle so I want to make sure this does not break anything.

**Comment by gjb2048** [comment]
Hi Bas,

The fix is a direct copy from bootstrapbase with the files of the same name, so should be 75% correct :).

Cheers,

Gareth

**Comment by bmbrands** [comment]
I might as well start merging and testing :)

**Comment by gjb2048** [comment]
Is it possible to checkout remote branch and test it without merging?

**Comment by bmbrands** [comment]
I think so yes. But it is easy enough to just merge en do testing right away. This one is simple enough to change since it is just one added less file :)

**Comment by gjb2048** [comment]
:)

**Pull request merged**
