### PR TITLE
Implement MDL-51013; suppress navbar button when custom menu is empty

### PR DESCRIPTION
**Pull request by OdyX**
Also provide a translation for the 'Toggle navigation' string.

### CODE REVIEW

**Comment by bmbrands** [comment]
Thanks Didier, excellent fix and an important improvement. Cool stuff

**Comment by bmbrands** [comment]
I made some small changes to the indenting to make sure it passed the Travis checks. Just so you know

**Comment by gjb2048** [comment]
Interesting :) - I looked at the code and the 'type' attribute is missing, so Shoehorn: https://github.com/gjb2048/moodle-theme_shoehorn/blob/master/classes/output/core_renderer.php#L132 and the W3C HTML for 'button': http://www.w3schools.com/tags/tag_button.asp

**Comment by bmbrands** [comment]
Thanks Gareth! You're right. I have added the type param

**Pull request merged**
