### PR TITLE
Collapsed Topics support for Bootstrap and Elegance.

### PR DESCRIPTION
**Pull request by gjb2048**
Hi Bas,

This provides Collapsed Topics columns support for both Bootstrap and Elegance.  This is to answer:

Is the 3.1.1.1 version of this great plugin support the Elegance theme? 
I cannot get more than one column to display with the elegance theme, or is it a theme issue? 

Many Thanks

Annick

on: https://moodle.org/plugins/format_topcoll

I made a judgement call on the new CSS file, clearly up to you to decide to move that sort of selector.

Cheers,

Gareth

### CODE REVIEW

**Comment by bmbrands** [comment]
Hi Gareth,

Would you mind moving the css to less/moodle/course.less ? weeks and topics are there too.

**Comment by gjb2048** [comment]
No problem.

**Comment by gjb2048** [comment]
Hi Bas,

Done.  Clearly re-running grunt compile has made 'improvements' that had not previously been compiled.

Cheers,

Gareth

**Comment by bmbrands** [comment]
hmm how weird. newer versions of stuff done by Grunt? Anyway happy to merge this :)

**Comment by gjb2048** [comment]
Thanks Bas.

All I did on the branch was change 'course.less' then 'npm install', then 'grunt compile'.

**Pull request merged**
