### PR TITLE
Add improvements to the project.

### PR DESCRIPTION
**Pull request by danilorb**
Add improvements to the project.

1 - Add partial folder to remove the repetition coding.

2 - Remove closing wrong div.

### CODE REVIEW

**Comment by bmbrands** [comment]
Hi Danilo,

Thanks for these. Well spotted on the popup closing div! I am not sure if the partials structure for the theme makes creating child themes based on this theme easier for developers. Could you tell me a bit more on why you added this?

**Comment by danilorb** [comment]
Hello Bas,

I work every day with development issues for Moodle.
I made this separation to improvements and easy maintenance.

Some files are also called several times in other files.
How parts: header, footer, head, ....

It is easier to change in one place than to change in many.

**Comment by gjb2048** [comment]
Hi Bas and Danilo,

I watch what's going on with Bootstrap as I appreciate the theme :).

The patch is ok, but it could be better for $CFG->themedir and existence in child theme file detection.  I've implemented and evolved two similar mechanisms in Essential and Shoehorn.  Lately using namespaces and automatic class loading, for example:

https://github.com/gjb2048/moodle-theme_essential/blob/master/layout/columns1.php#L28

and

https://github.com/gjb2048/moodle-theme_essential/blob/master/classes/toolbox.php#L68-L96

Whereby the child theme layouts can use the same call:

https://github.com/gjb2048/moodle-theme_essential/blob/master/essentials/layout/frontpage.php#L27

But then implement their own version, such as:

https://github.com/gjb2048/moodle-theme_essential/blob/master/essentials/layout/includes/header.php

This makes the concept of inheritance possible in what is effectively a more functional and procedural programming language.  Now all child themes need to do is supply the alterations.  This helps two fold:

1. You still get all of the functionality of the parent theme and need only override the changes.
2. When the parent theme updates then you benefit from the changes, there is often no changes to be made to the child theme and critically you don't have to reapply your customisations again.

Cheers,

Gareth

**Comment by danilorb** [comment]
Hello Gareth,

The purpose of making these changes is to make life easier for everyone.
I know several people who use the project and liked the idea of separation.

I particularly do this in all projects.

I think it would be nice to apply something all people like to use and makes life easier for all developers so.

**Comment by gjb2048** [comment]
Hi Danilo,

Umm, I know! :) - that's why I've implemented my own mechanism as described.

Cheers,

Gareth

**Comment by danilorb** [comment]
I know,

But many people do not know how to apply this mechanism in order.

The idea is make life easier for developers.

**Comment by gjb2048** [comment]
Ok, but why are you trying to convince me when I'm already convinced?  In fact the patch could be better as already indicated.

**Comment by danilorb** [comment]
I'm not trying to convince. hehe
I'm just explaining my point of view. =)

**Comment by bmbrands** [comment]
I think for now I would prefer keeping things the way they are. I understand code repetition should generally be avoided. The 2 layout files in the bootstrap theme which look most alike are secure.php and default.php. When comparing columns3.php and secure.php in the clean theme I noticed the contents of elements like the header are different. So when slicing up these files you would need separate partials for each layout file which does not solve the code repetition part.  

For now I think its best to focus on the less / css part of the theme and trying to get a stable version for Moodle 2.9. Maybe on the next release we can focus on simplification of the layout files.

Of course I did use your fix for the missing div @danilorb ! And thanks @gjb2048 for showing the solution you used in Essential. And if you feel I am totally wrong on this point do tell me!

Cheers!

**Comment by danilorb** [comment]
Hello Bas,

I understand you you want to keep the theme stable.
As discussed with the @gjb2048 , this was an improvement that I think needed for developers using the theme.

Only here where I live (Rio de Janeiro / Brazil) know several people who use the structure so that I rode.

But feel free if you want to use the structure created.

Thank you for your attention, and can be sure that I will help Moodle themes going forward.

**Comment by danilorb** [comment]
Hello Bas,

I took and added the config editor to the project.
I think that's very important to indentation and pattern.

**Pull request closed without merging**
